export const DATA = [
  {
    id: 1,
    emoji: "🍎",
    nameEnglish: "apple",
    nameKatakana: "リンゴ",
    nameHiragana: "りんご",
  },
  {
    id: 2,
    emoji: "🍊",
    nameEnglish: "orange",
    nameKatakana: "オレンジ",
    nameHiragana: "おれんじ",
  },
  {
    id: 3,
    emoji: "🍋",
    nameEnglish: "lemon",
    nameKatakana: "レモン",
    nameHiragana: "れもん",
  },
  {
    id: 4,
    emoji: "🍇",
    nameEnglish: "grapes",
    nameKatakana: "ブドウ",
    nameHiragana: "ぶどう",
  },
  {
    id: 5,
    emoji: "🍓",
    nameEnglish: "strawberry",
    nameKatakana: "ストロベリー",
    nameHiragana: "すとろべりー",
  },
  {
    id: 6,
    emoji: "🥝",
    nameEnglish: "kiwi fruit",
    nameKatakana: "キウイフルーツ",
    nameHiragana: "きういふるーつ",
  },
  {
    id: 7,
    emoji: "🍍",
    nameEnglish: "pineapple",
    nameKatakana: "パイナップル",
    nameHiragana: "ぱいなっぷる",
  },
  {
    id: 8,
    emoji: "🥭",
    nameEnglish: "mango",
    nameKatakana: "マンゴー",
    nameHiragana: "まんごー",
  },
  {
    id: 9,
    emoji: "🍑",
    nameEnglish: "peach",
    nameKatakana: "ピーチ",
    nameHiragana: "ぴーち",
  },
  {
    id: 10,
    emoji: "🍒",
    nameEnglish: "cherries",
    nameKatakana: "チェリー",
    nameHiragana: "ちぇりー",
  },
  {
    id: 11,
    emoji: "🍅",
    nameEnglish: "tomato",
    nameKatakana: "トマト",
    nameHiragana: "とまと",
  },
  {
    id: 12,
    emoji: "🍆",
    nameEnglish: "eggplant",
    nameKatakana: "ナス",
    nameHiragana: "なす",
  },
  {
    id: 13,
    emoji: "🥑",
    nameEnglish: "avocado",
    nameKatakana: "アボカド",
    nameHiragana: "あぼかど",
  },
  {
    id: 14,
    emoji: "🥦",
    nameEnglish: "broccoli",
    nameKatakana: "ブロッコリー",
    nameHiragana: "ぶろっこりー",
  },
  {
    id: 15,
    emoji: "🥒",
    nameEnglish: "cucumber",
    nameKatakana: "キュウリ",
    nameHiragana: "きゅうり",
  },
  {
    id: 16,
    emoji: "🌶️",
    nameEnglish: "hot pepper",
    nameKatakana: "トウガラシ",
    nameHiragana: "とうがらし",
  },
  {
    id: 17,
    emoji: "🌽",
    nameEnglish: "ear of corn",
    nameKatakana: "トウモロコシ",
    nameHiragana: "とうもろこし",
  },
  {
    id: 18,
    emoji: "🥕",
    nameEnglish: "carrot",
    nameKatakana: "ニンジン",
    nameHiragana: "にんじん",
  },
  {
    id: 19,
    emoji: "🥔",
    nameEnglish: "potato",
    nameKatakana: "ジャガイモ",
    nameHiragana: "じゃがいも",
  },
  {
    id: 20,
    emoji: "🍠",
    nameEnglish: "sweet potato",
    nameKatakana: "サツマイモ",
    nameHiragana: "さつまいも",
  },
  {
    id: 21,
    emoji: "🧅",
    nameEnglish: "onion",
    nameKatakana: "タマネギ",
    nameHiragana: "たまねぎ",
  },
  {
    id: 22,
    emoji: "🧄",
    nameEnglish: "garlic",
    nameKatakana: "ニンニク",
    nameHiragana: "にんにく",
  },
  {
    id: 23,
    emoji: "🥬",
    nameEnglish: "leafy green",
    nameKatakana: "リーフィーグリーン",
    nameHiragana: "りーふぃーぐりーん",
  },
  {
    id: 24,
    emoji: "🥗",
    nameEnglish: "green salad",
    nameKatakana: "サラダ",
    nameHiragana: "さらだ",
  },
  {
    id: 25,
    emoji: "🍕",
    nameEnglish: "pizza",
    nameKatakana: "ピザ",
    nameHiragana: "ぴざ",
  },
  {
    id: 26,
    emoji: "🍔",
    nameEnglish: "hamburger",
    nameKatakana: "ハンバーガー",
    nameHiragana: "はんばーがー",
  },
  {
    id: 27,
    emoji: "🌭",
    nameEnglish: "hot dog",
    nameKatakana: "ホットドッグ",
    nameHiragana: "ほっとどっぐ",
  },
  {
    id: 28,
    emoji: "🥪",
    nameEnglish: "sandwich",
    nameKatakana: "サンドイッチ",
    nameHiragana: "さんどいっち",
  },
  {
    id: 29,
    emoji: "🌮",
    nameEnglish: "taco",
    nameKatakana: "タコス",
    nameHiragana: "たこす",
  },
  {
    id: 30,
    emoji: "🌯",
    nameEnglish: "burrito",
    nameKatakana: "ブリトー",
    nameHiragana: "ぶりとー",
  },

  {
    id: 31,
    emoji: "🫔",
    nameEnglish: "tamale",
    nameKatakana: "タマレ",
    nameHiragana: "たまれ",
  },
  {
    id: 32,
    emoji: "🥙",
    nameEnglish: "stuffed flatbread",
    nameKatakana: "フラットブレッド",
    nameHiragana: "ふらっとぶれっど",
  },
  {
    id: 33,
    emoji: "🧆",
    nameEnglish: "falafel",
    nameKatakana: "ファラフェル",
    nameHiragana: "ふぁらふぇる",
  },
  {
    id: 34,
    emoji: "🥚",
    nameEnglish: "egg",
    nameKatakana: "タマゴ",
    nameHiragana: "たまご",
  },
  {
    id: 35,
    emoji: "🍳",
    nameEnglish: "cooking",
    nameKatakana: "リョウリ",
    nameHiragana: "りょうり",
  },
  {
    id: 36,
    emoji: "🥞",
    nameEnglish: "pancakes",
    nameKatakana: "パンケーキ",
    nameHiragana: "ぱんけーき",
  },
  {
    id: 37,
    emoji: "🧇",
    nameEnglish: "waffle",
    nameKatakana: "ワッフル",
    nameHiragana: "わっふる",
  },
  {
    id: 38,
    emoji: "🥓",
    nameEnglish: "bacon",
    nameKatakana: "ベーコン",
    nameHiragana: "べーこん",
  },
  {
    id: 39,
    emoji: "🥩",
    nameEnglish: "cut of meat",
    nameKatakana: "カットオブミート",
    nameHiragana: "かっとおぶみーと",
  },
  {
    id: 40,
    emoji: "🍗",
    nameEnglish: "poultry leg",
    nameKatakana: "ポルトリーレッグ",
    nameHiragana: "ぽるとりーれっぐ",
  },
  {
    id: 41,
    emoji: "🍖",
    nameEnglish: "meat on bone",
    nameKatakana: "ミートオンボーン",
    nameHiragana: "みーとおんぼーん",
  },
  {
    id: 42,
    emoji: "🦴",
    nameEnglish: "bone",
    nameKatakana: "ボーン",
    nameHiragana: "ぼーん",
  },
  {
    id: 43,
    emoji: "🍤",
    nameEnglish: "fried shrimp",
    nameKatakana: "エビフライ",
    nameHiragana: "えびふらい",
  },
  {
    id: 44,
    emoji: "🍣",
    nameEnglish: "sushi",
    nameKatakana: "スシ",
    nameHiragana: "すし",
  },
  {
    id: 45,
    emoji: "🍱",
    nameEnglish: "bento box",
    nameKatakana: "ベントウ",
    nameHiragana: "べんとう",
  },
  {
    id: 46,
    emoji: "🍥",
    nameEnglish: "fish cake with swirl",
    nameKatakana: "ナルト",
    nameHiragana: "なると",
  },
  {
    id: 47,
    emoji: "🍙",
    nameEnglish: "rice ball",
    nameKatakana: "オニギリ",
    nameHiragana: "おにぎり",
  },
  {
    id: 48,
    emoji: "🍘",
    nameEnglish: "rice cracker",
    nameKatakana: "センベイ",
    nameHiragana: "せんべい",
  },
  {
    id: 49,
    emoji: "🍚",
    nameEnglish: "cooked rice",
    nameKatakana: "ゴハン",
    nameHiragana: "ごはん",
  },
  {
    id: 50,
    emoji: "🍛",
    nameEnglish: "curry rice",
    nameKatakana: "カレーライス",
    nameHiragana: "かれーらいす",
  },
  {
    id: 51,
    emoji: "🍜",
    nameEnglish: "steaming bowl",
    nameKatakana: "ラーメン",
    nameHiragana: "らーめん",
  },
  {
    id: 52,
    emoji: "🍝",
    nameEnglish: "spaghetti",
    nameKatakana: "スパゲッティ",
    nameHiragana: "すぱげってぃ",
  },
  {
    id: 53,
    emoji: "🍠",
    nameEnglish: "roasted sweet potato",
    nameKatakana: "ヤキイモ",
    nameHiragana: "やきいも",
  },
  {
    id: 54,
    emoji: "🍢",
    nameEnglish: "oden",
    nameKatakana: "オデン",
    nameHiragana: "おでん",
  },
  {
    id: 55,
    emoji: "🍡",
    nameEnglish: "dango",
    nameKatakana: "ダンゴ",
    nameHiragana: "だんご",
  },
  {
    id: 56,
    emoji: "🥟",
    nameEnglish: "dumpling",
    nameKatakana: "ギョーザ",
    nameHiragana: "ぎょーざ",
  },
  {
    id: 57,
    emoji: "🥠",
    nameEnglish: "fortune cookie",
    nameKatakana: "フォーチュンクッキー",
    nameHiragana: "ふぉーちゅんくっきー",
  },
  {
    id: 58,
    emoji: "🥡",
    nameEnglish: "takeout box",
    nameKatakana: "テイクアウトボックス",
    nameHiragana: "ていくあうとぼっくす",
  },
  {
    id: 59,
    emoji: "🦀",
    nameEnglish: "crab",
    nameKatakana: "カニ",
    nameHiragana: "かに",
  },
  {
    id: 60,
    emoji: "🦞",
    nameEnglish: "lobster",
    nameKatakana: "ロブスター",
    nameHiragana: "ろぶすたー",
  },
];
